version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
        environment:
            xpack.security.enabled: "false"
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana-x-pack:6.2.4
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - elasticsearch
    logstash:
        build:
            context: ..
            dockerfile: docker-elk/logstash-with-x-pack.Dockerfile
        ports:
            - "9600:9600"
        volumes:
            - ../log-dropzone/:/logs
        networks:
            - elastic
        depends_on:
            - elasticsearch
networks:
    elastic:
